# Generated by Django 5.1.4 on 2025-01-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-published_at"]},
        ),
    ]
